const constants =  {
    FETCH_ALL_RECIPES : 'FETCH_ALL_RECIPES',
    FETCH_RECIPE : 'FETCH_RECIPE',
    SEARCH_RECIPES : 'SEARCH_RECIPES',
    FETCH_ALL_CATEGORIES: 'FETCH_ALL_CATEGORIES'
}

export default constants;