const constants =  {
    RECIPES_PENDING : 'RECIPES_PENDING',
    RECIPES_SUCCESS : 'RECIPES_SUCCESS',
    RECIPES_FAILED : 'RECIPES_FAILED',

    SEARCH_RECIPES_PENDING: 'SEARCH_RECIPES_PENDING',
    SEARCH_RECIPES_SUCCESS: 'SEARCH_RECIPES_SUCCESS',
    SEARCH_RECIPES_FAILED: 'SEARCH_RECIPES_FAILED',

    CATEGORIES_PENDING : 'CATEGORIES_PENDING',
    CATEGORIES_SUCCESS : 'CATEGORIES_SUCCESS',
    CATEGORIES_FAILED : 'CATEGORIES_FAILED',

    ADDING_CATEGORY_PENDING: 'ADDING_CATEGORY_PENDING',
    ADDING_CATEGORY_SUCCESS: 'ADDING_CATEGORY_SUCCESS',
    ADDING_CATEGORY_FAILED: 'ADDING_CATEGORY_FAILED',

    UPDATE_CATEGORY_PENDING: 'UPDATE_CATEGORY_PENDING',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAILED: 'UPDATE_CATEGORY_FAILED',

    DELETE_CATEGORY_PENDING: 'DELETE_CATEGORY_PENDING',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILED: 'DELETE_CATEGORY_FAILED',

    ADDING_RECIPE_PENDING: 'ADDING_RECIPE_PENDING',
    ADDING_RECIPE_SUCCESS: 'ADDING_RECIPE_SUCCESS',
    ADDING_RECIPE_FAILED: 'ADDING_RECIPE_FAILED',

    UPDATE_RECIPE_PENDING: 'UPDATE_RECIPE_PENDING',
    UPDATE_RECIPE_SUCCESS: 'UPDATE_RECIPE_SUCCESS',
    UPDATE_RECIPE_FAILED: 'UPDATE_RECIPE_FAILED',

    DELETE_RECIPE_PENDING: 'DELETE_RECIPE_PENDING',
    DELETE_RECIPE_SUCCESS: 'DELETE_RECIPE_SUCCESS',
    DELETE_RECIPE_FAILED: 'DELETE_RECIPE_FAILED',

    LOGIN_USUARIO_PENDING: 'LOGIN_USUARIO_PENDING',
    LOGIN_USUARIO_SUCCESS: 'LOGIN_USUARIO_SUCCESS',
    LOGIN_USUARIO_FAILED: 'LOGIN_USUARIO_FAILED',

    LOGOUT: 'LOGOUT',
}

export default constants;