const constants =  {
    RECIPES_PENDING : 'RECIPES_PENDING',
    RECIPES_SUCCESS : 'RECIPES_SUCCESS',
    RECIPES_FAILED : 'RECIPES_FAILED',

    SEARCH_RECIPES_PENDING: 'SEARCH_RECIPES_PENDING',
    SEARCH_RECIPES_SUCCESS: 'SEARCH_RECIPES_SUCCESS',
    SEARCH_RECIPES_FAILED: 'SEARCH_RECIPES_FAILED',

    SEARCH_RECIPES : 'SEARCH_RECIPES',
    FETCH_ALL_CATEGORIES: 'FETCH_ALL_CATEGORIES'
}

export default constants;